apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
   app: nginx

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: nginxrc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    containers:
      - name: nginx
        image: nginx
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
    volumes:
      - name: nginx-config
        configMap:
          name: nginx-config        
