apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "fullname" . }}-kafka
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  serviceName: "broker"
  replicas: {{ .Values.kafka.statefulSet.replicaCount }}
  template:
    metadata:
      labels:
        kubeless: {{ template "fullname" . }}-kafka
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: broker
        image: "{{ .Values.kafka.statefulSet.image.repository }}:{{ .Values.kafka.statefulSet.image.tag }}"
        imagePullPolicy: {{ .Values.kafka.statefulSet.image.pullPolicy }}
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: broker.kubeless
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_PORT
          value: "9092"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper.kubeless:2181
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        ports:
        - containerPort: 9092
        resources: {}
        volumeMounts:
        - name: datadir
          mountPath: /bitnami/kafka/data
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
