# Default values for kubeless.

## Controller configuration
controller:
  deployment:
    replicaCount: 1
    image:
      repository: bitnami/kubeless-controller@sha256
      tag: 53592e0f023353665569313a1662a3aff18141e48caf4beca54d68436e71e0dc
      pullPolicy: IfNotPresent

## UI configuration
ui:
  deployment:
    replicaCount: 1
    ui:
      image:
        repository: bitnami/kubeless-ui
        tag: v0.1.0
        pullPolicy: IfNotPresent
    proxy:
      image:
        repository: kelseyhightower/kubectl
        tag: 1.4.0
        pullPolicy: IfNotPresent

  service:
    name: ui-port
    type: NodePort
    externalPort: 3000

## Zookeeper configuration
zookeeper:
  statefulSet:
    replicaCount: 1
    image:
      repository: bitnami/zookeeper@sha256
      tag: f66625a8a25070bee18fddf42319ec58f0c49c376b19a5eb252e6a4814f07123
      pullPolicy: IfNotPresent

## Kafka configuration
kafka:
  statefulSet:
    replicaCount: 1
    image:
      repository: bitnami/kafka@sha256
      tag: 0c4be25cd3b31176a4c738da64d988d614b939021bedf7e1b0cc72b37a071ecb
      pullPolicy: IfNotPresent
