
common:
  imagePullPolicy: Always

security:
  image: galacticfog/gestalt-security:release-1.4.3
  exposedServiceType: NodePort
  hostname: gestalt-security.gestalt-system
  port: 9455
  protocol: http
  adminUser: "gestalt-admin"
  adminPassword: "QzUzhAqP2s1yHvcN"
  databaseName: gestalt-security

rabbit:
  image: galacticfog/rabbit:release-1.4.3
  hostname: gestalt-rabbit.gestalt-system
  port: 5672
  httpPort: 15672

meta:
  image: galacticfog/gestalt-meta:release-1.4.5
  exposedServiceType: NodePort
  hostname: gestalt-meta.gestalt-system
  port: 10131
  protocol: http
  databaseName: gestalt-meta

laser:
  image: galacticfog/gestalt-laser:release-1.4.2
  databaseName: laser-db
  cpu: 0.25
  memory: 512
  executorImages:
    dotNet: 
    golang: 
    js: galacticfog/gestalt-laser-executor-js:release-1.4.2
    nodejs: galacticfog/gestalt-laser-executor-nodejs:release-1.4.2
    jvm: 
    python: 
    ruby: 

gatewayManager:
  image: galacticfog/gestalt-api-gateway:release-1.4.2
  databaseName: gateway-db

kong:
  image: galacticfog/kong:release-1.4.2
  databaseName: kong-db

ui:
  image: galacticfog/gestalt-ui-react:release-1.4.5
  exposedServiceType: NodePort
  ingress:
    host: gestalt.local

policy:
  image: galacticfog/gestalt-policy:release-1.4.2

# Database configuration:
# Provision an internal database
# TODO - use this to determine whether to provision postgres as container
#provision-internal-db: true

postgresql:
  postgresUser: postgres
  postgresPassword: "g3wiOK1t65PPvqcx"
  postgresDatabase: postgres
  persistence:
    size: 100Mi
    storageClass: "gestalt-postgresql-volume"
  resources:
    limits:
      memory: 256Mi
      cpu: 100m
  service:
    port: 5432
    type: ClusterIP

# Internal DB settings
db:
  # Hostname must be fully qualified for Kong service
  hostname: gestalt-postgresql.gestalt-system.svc.cluster.local
  port: 5432
  username: postgres
  password: "g3wiOK1t65PPvqcx"
  databaseName: postgres

installer:
  image: galacticfog/gestalt-installer:release-1.4.5
  mode: 
  useDynamicLoadBalancers: No
  externalGateway:
    dnsName: gtw1.gestalt.local
    protocol: http
    kongServiceName: kng
  kubeconfig: YXBpVmVyc2lvbjogdjEKY2x1c3RlcnM6Ci0gY2x1c3RlcjoKICAgIGNlcnRpZmljYXRlLWF1dGhvcml0eS1kYXRhOiBMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VNMWVrTkRRV01yWjBGM1NVSkJaMGxDUVZSQlRrSm5hM0ZvYTJsSE9YY3dRa0ZSYzBaQlJFRldUVkpOZDBWUldVUldVVkZFUlhkd2RHRlhOWEFLWVROV2FWcFZUa0pOUWpSWVJGUkZORTFFUlhkUFJFVjVUVlJOZDAxc2IxaEVWRWswVFVSRmQwNXFSWGxOVkUxM1RXeHZkMFpVUlZSTlFrVkhRVEZWUlFwQmVFMUxZbGRzZFdGWGRERlpiVlpFVVZSRFEwRlRTWGRFVVZsS1MyOWFTV2gyWTA1QlVVVkNRbEZCUkdkblJWQkJSRU5EUVZGdlEyZG5SVUpCVDB4dENuRTVLMUIyWW1oUlRFSldRbHBZWmpKcGVHNVZXR1EzVUhsUGJFWnlhSEpRYWtwVWFEa3JURVkxUVhwalRVa3dVbmd5T1hSNFV6ZGlaRFp4T1dSRFJUTUtXRzFIV2tOemFIUjNPQzltUm5ZMlRFUnFVbXRyVDFwbmJHTXlZVUZEY214WGR6RkZWMmhRTkVGemVucDFWekZtYkVWWmFVOVljVTVGZVU5Nk55OUVNUW94Tm5CekwwZHFRMlJpY21wU2RIVlNlblJYTVc5RWJERXpVbEJtUkUxT1lVVmFlakp3Ym1rMVVpdEZXbkJSVUhSdFkwNDFTWFp0WkU1M1UwNVlRM1EzQ2xGcVdEVlBOVWg0TldwcGFsTnhaM0JEYnpKMlNIWmtPVkZwWkcxcVZXOXdXamxQVjNNMWRGUjRXVmRVT1RGMVNtMXlZbFZuYVhKbU9EUklhbk5NYkhrS1NFODFLME5IY21KeVQzRlhLeXRzUzAxYVZUUmpWM0o1WWs4MlNXTkZNMmxHYXpsMGEwVlBkVm92WVRCYWF5dHplWFJ1U2pWVmRIUjVlbUZrWlZKbFR3cHZSeTlSUlZaV09XUTFkVTU0WVhWb2NtNUZRMEYzUlVGQllVNURUVVZCZDBSbldVUldVakJRUVZGSUwwSkJVVVJCWjB0clRVSXdSMEV4VldSS1VWRlhDazFDVVVkRFEzTkhRVkZWUmtKM1RVTkNaMmR5UW1kRlJrSlJZMFJCVkVGUVFtZE9Wa2hTVFVKQlpqaEZRbFJCUkVGUlNDOU5RVEJIUTFOeFIxTkpZak1LUkZGRlFrTjNWVUZCTkVsQ1FWRkJlWGRSV0VWelZETlVlaTl2WXl0TlNXdDZSV2h6WTFWT2JGY3hkMjFtZDNWTFIwcHlTMUZZTldSSVdraGtMMFJ6YkFvM05YUm5ObGh4YUVKNFN6aHVNMDVSU0c4eGNHdFpiVE5LTHpKS1ZUVnRWbWt6ZERkMFJXbDNVbU00WkRFNWNIUlNaUzlWTVhWeVRWcEhhWEZUWkRsdENrYzNaWFZMZVhKa1oxQkJRVEphV1dWcWFuZEVjVmNyV1hZNE9IcDRVWEJPVVZodlZEaGxSWEZNTm5Nd01GcHJWa1pTVTNCRFpsTkRjbVJIUTAxT1Mwa0tiVmxZWTBKQlVrMURVRXRRTTNWbU5sZ3pXakp3UzJkRE0yaENlR2RoTTBORGMwdFJPRTFCTlhsWVVVTklabkY0U0VjdlIwSmtWRUpZTlUxTWNUTmhhd28zV2pCR2MwZFRWMVkwVXl0bVpsTlpZa1V6TVhsT1JUTnBPVlpJYmxKV2RERm1NMU5WYWtGQlIyeDNPRWM0VlZSV1pEVndPRFUyVTFkc1EwcEJkbU5UQ2pSRlNVVk5kbWxFYTNSME0wOVFWR1ZxWm13dk0yMWFkbkZEUVZScGFtVmFZWFJVZEFvdExTMHRMVVZPUkNCRFJWSlVTVVpKUTBGVVJTMHRMUzB0Q2c9PQogICAgc2VydmVyOiBodHRwczovLzE5Mi4xNjguNjQuNjo4NDQzCiAgbmFtZTogbWluaWt1YmUKY29udGV4dHM6Ci0gY29udGV4dDoKICAgIGNsdXN0ZXI6IG1pbmlrdWJlCiAgICB1c2VyOiBtaW5pa3ViZQogIG5hbWU6IG1pbmlrdWJlCmN1cnJlbnQtY29udGV4dDogbWluaWt1YmUKa2luZDogQ29uZmlnCnByZWZlcmVuY2VzOiB7fQp1c2VyczoKLSBuYW1lOiBtaW5pa3ViZQogIHVzZXI6CiAgICBjbGllbnQtY2VydGlmaWNhdGUtZGF0YTogTFMwdExTMUNSVWRKVGlCRFJWSlVTVVpKUTBGVVJTMHRMUzB0Q2sxSlNVUkJSRU5EUVdWcFowRjNTVUpCWjBsQ1FXcEJUa0puYTNGb2EybEhPWGN3UWtGUmMwWkJSRUZXVFZKTmQwVlJXVVJXVVZGRVJYZHdkR0ZYTlhBS1lUTldhVnBWVGtKTlFqUllSRlJGTkUxRVJYZFBWRVUwVFZSck1FMUdiMWhFVkVVMVRVUkZkMDlVUlRSTlZHc3dUVVp2ZDAxVVJWaE5RbFZIUVRGVlJRcERhRTFQWXpOc2VtUkhWblJQYlRGb1l6TlNiR051VFhoR2FrRlZRbWRPVmtKQlRWUkVWekZ3WW0xc2NtUlhTbXhNV0ZaNldsaEpkMmRuUldsTlFUQkhDa05UY1VkVFNXSXpSRkZGUWtGUlZVRkJORWxDUkhkQmQyZG5SVXRCYjBsQ1FWRkVjVTB2TjBGNldISlpTRFZCUTA1NldsQkpaMk5FWWpjNFpFMWpiVWNLTlU5S1dVRk9PRU41VUZSVFZYVjFWRWQ2TTNGbFpGZHBVRlJ3YXprek1uazNNblpYYXpRdlNuaDBNRFp0YlZwRmJUUktXbFV4V2sxS1VGWlZOakpUYkFwVmRqbEpRMk51ZG5WU1VYSnZRV3hVTm1SRVFVRnRNMnhaSzA1NGRuQkxMMFZKY1ZORk0wMWphR3hyZHpOb01IQmhhbVZpVWtvM1VsRm5Sa3N3VkUxU0NraE1NVmxIYm5sQ1lYWlBObkJrV2xaUU4wUmlSMGx3ZUVkS2FrNTFRbU5aSzNCUmMxbHRPRkU1TkdkSVMxWmFlSGR2TTJsQ1VrbHRRMk5uT0dRd2N6Y0tOMGxCTDNoWVZ6aDNObUUzZVdsQllURkhlRU5TZFUxalF6UjFhMVp3WWtoNFdXNUJXRGQwYURCRk1qUXlTRlpVYmxGMk5HUlZSWFphUlRKR1RqVmlWd3B0WjA1RlYwSm9ORXhVZWtZMFNUWkxWMk41Vkc4eU1VWXpaRFI2Wmtac09YZHBha05EYzJ0V1FrcE5UMWxtVTNSRlEyTk5WRzA1YmtGblRVSkJRVWRxQ2xCNlFUbE5RVFJIUVRGVlpFUjNSVUl2ZDFGRlFYZEpSbTlFUVdSQ1owNVdTRk5WUlVacVFWVkNaMmR5UW1kRlJrSlJZMFJCVVZsSlMzZFpRa0pSVlVnS1FYZEpkMFJCV1VSV1VqQlVRVkZJTDBKQlNYZEJSRUZPUW1kcmNXaHJhVWM1ZHpCQ1FWRnpSa0ZCVDBOQlVVVkJaVkZwVXk5cGVtbHBWVVEzY2tSVVFRcGlVbWR6YUhadlV6WjJORmxIV1hKV1dtWldOamRQU2pBNE9VaERjVE5aT0dkWVJ6Sk5hR3N6VmxZdmJURTBNMVp3V1VWdFJESTRaM0Z0Um5sdVNtWnpDbmw2TVRaMGEwRlllV2RDWTFCdlVVcFVZbGRZVnpSUU9FaHVVakEzU21oNGRGTkZOSE4zZEZrMk5FNU5Obm9yVFhscFJWVlFZVWRpUlhwb1kwVnlXbGtLVFdOSVJsZ3dVMk5oUzJOSFVGZzRWa28yYmpab1NUTTVObFl5TTJadlNtOVNNMVZ6VnpWR05XZHhUMGxJTkdaMGJGSnNURnBvVGpjMVYzazVTVVZNYVFvdmVFNTVURk0zWVc0cmJqaGpkQ3N2WjFaTmNtVmlRVmRHY0VKa1VVRklWVkpXYzBsNGJHa3JUemhZV0dOdmJEbGxNbFJ2ZFdjNFZrVlpZbVp6YlhWUUNubEhRWGhLUlVsT1RXd3ZTRzU0V0ZabU5uZERURzVaTjBKclNFaHpVVGRIV0VrdmJqZHhWa3M1VkhNd1FrVmtia3hQUlRaUFNtcDRZMDFWVVdseFNYa0tZbTFRWTNWQlBUMEtMUzB0TFMxRlRrUWdRMFZTVkVsR1NVTkJWRVV0TFMwdExRbz0KICAgIGNsaWVudC1rZXktZGF0YTogTFMwdExTMUNSVWRKVGlCU1UwRWdVRkpKVmtGVVJTQkxSVmt0TFMwdExRcE5TVWxGY0VGSlFrRkJTME5CVVVWQk5tcFFLM2ROTVRZeVFpdFJRV3BqTWxSNVNVaEJNaXN2U0ZSSVNtaDFWR2xYUVVSbVFYTnFNREJzVEhKcmVITTVDalp1YmxadmFqQTJXbEJrT1hOMU9YSXhjRTlRZVdOaVpFOXdjRzFTU25WRFYxWk9WMVJEVkRGV1QzUnJjRlpNTDFOQmJrbzNOMnRWU3paQlNsVXJibEVLZDBGS2REVlhVR3BqWWpaVGRuaERTMnRvVG5wSVNWcGFUVTQwWkV0WGJ6TnRNRk5sTUZWSlFsTjBSWHBGVW5rNVYwSndPR2RYY25wMWNWaFhWbFFyZHdveWVHbExZMUpwV1hwaVoxaEhVSEZWVEVkS2RrVlFaVWxDZVd4WFkyTkxUalJuVlZOS1oyNUpVRWhrVEU4cmVVRlFPRll4ZGsxUGJYVTRiMmRIZEZKekNsRnJZbXBJUVhWTWNFWmhWM2c0VjBwM1JpczNXV1JDVG5WT2FERlZOVEJNSzBoV1Frd3lVazVvVkdWWE1YQnZSRkpHWjFsbFF6QTRlR1ZEVDJsc2JrMEthelpPZEZKa00yVk5NM2hhWm1OSmIzZG5ja3BHVVZOVVJHMUlNSEpTUVc1RVJUVjJXbmRKUkVGUlFVSkJiMGxDUVZGRE1HSnNOV3AwTW5CbGRYVkpPUXBqY2k5aFl6QkxiaXRTTVhCd2IwOHhPSFozVjBKSldFeEtXSEpJTVhFME5qVlJMM05hZGxOYVV6QmhSSEIwUVcxWVMwaGtOMFV3YjJwS1lTOXZWbWROQ201NWJuSkhNMDExYzI5S00yRXJjR05ITDJOclZISmFUMmN5TTNkMGFHazFiSHBqUmpGc2JFbEZielpXWjA1aFdtTkhjbmhaZURaYU5sUTRjR3RPVlhrS2NFOTNNa3ROVjJGUVdtMHhVa1J3ZEdkd1F6RkpZVXQxUzJaSFpqVnpOVkZ6VVhadFpXTjBRM1UxU3pCa1ZYTndXbUpYU2pSUkwzQmpjalF6VFRCcGRRcE9aazVUT1c1UFRVeHpTblV5ZG1GcGVuTnNhR0Z6U2twR1UxWXdiWFZyUlZGUmFVUkRLMDlvVURGRlN6TlJTV0Y2UjNsMFNqTm1iMDAyWmxZeGNuWjRDazVaU2l0Rk4zQlJRMnBhYjNCVFJucHZja3BrY1dWR2JVeFdZMGxxZVV3MGJsWk9XRTltUkRkMGVFUjNVU3R4VDBrNWNUWnBVR05CTms5cVVXbERMMGdLVURCRldIQmFTMmhCYjBkQ1FWQlBhV1pKUVU1MU5rWnNTa1I1TTFkQmMySkphbkV4ZUdwQ1YxVmpRV2hYTnpKa1QxVmxhUzlsWmpGS1JuUlNkMWsyZEFwVVZtWTBWbEpGYWpOUFNXNUVhRmRsUm1jM2JuSlRkazgwZEdsc2FWSmpOMEV3Y2tjM2VFaHVXa1FyZWtzclNFeFVaall4WmpJMmRWTnRkRU5hU1ZCMENrcGlka2hzZDBNMlp6aGFTWEpaUkdoTlpVWkJTamxZVGxkelRHaHRiemRhZFZkeVNGRkVOM0JCTmpaMGRtOXBOa2t4UlhCRWVsVm1RVzlIUWtGUVdWY0tPWGhhWW01bWRuRmlUMlF4ZGpKMlltaHNkVmxVWm1nM1pqWlVTRGR0TjFWclJEVk9URTlCVFhWU2EwSlZVVU5RYzBoNVdUWklaekY0VVZKc2NtbEdSUXBqVlM4eFRIQjBOakkyVDJaRFRrUnFhRTh5YlVWelR5dG1VR2RhZURkUlpGVXZhVEZhTDNaQ04xZDZVbU5qTXpKUmRGWnJjM2hCV1U1RE5IWXllVmRPQ25CNU9ITnRUak5hVFZWNVRIVjBkVWsxVmtWSE0zTllTME0yWTFoS1QzQXdkMEpMTURSWVV6VkJiMGRCWmxaVlVGZDNhVEZvTVdSNWFIUkhRM1F5VUdvS0wyWlFXVEp5UkhSTFZIUXZOa1pHYWxWQ2FtNUxWbUZSZEROSFpHTjJjSGRIVm5Ock1UaGFkRTFQU1V0bGRFSjVXa2xUUjB3d01HdHZXRXN5ZWxnMlRRcFBVVWRTY0hSSk1GaG9hV0k0U0VsWU1ETnZiVGRvWXpOTVYzQm5USGRZYlV4WE1rWnVkR2hWVW1OTVNtcHpNVXRVWVdkc1ZtWldiMUpYZVhSb0swMHhDbGxXY2xSRlFXNXhNMUZsUVZKMlNVdHFVWFpyVTA0d1EyZFpSVUYxU21kNFkwVjJOVVJsWVdwSGJIaDNORzA0YUUxalVHeGxUMkp4YzB0b2IyRnBjRFFLY1UxTmNsUnJWVGc0TUhwU1ptbEtTM1ZMZG1Ga1drZG1NemxUUmpoa05YUlJVbFZvYVU4NU0yOW9la0psUXl0NWJuSkdZMnRuYUhCd1drWjRRU3RMWXdwQmIzWlNTRVZCZWpST1UySkZWM2RSV21oSVRGZzVPVWxDVURGUk0ySkxUVWhuTjA0dlJuWllXbmgyU2xweVVXaHFPRFJtWmxNME5UTXpVekE1Ulc1MkNtRm9hbFZ3WTBWRFoxbENVMGd3VW5OdFNVaDBhV3RrUTA1RmFucHVhRkZxT0hwRlJrSjZNWFpqT1VOU2NsaG5VRzVLUkZWaFUyODBOVmhxYkZoa2Iyd0tlVzVPTms5T2VsTmpVMEk0Y3pkRGIyRkZkRUpqVkN0dFIxazJaelI0UkdzMVpqWjRRMncxT1V4SVEzaFFVSGhrWWpZME5YSmpiVFpyYkhkdk1sVTVkZ3BZTDNjNGFtSjROa2d2TUZWVFpsQlJSRzlUYTBocVJUUXpZM3B5VW1kNlUyY3lSM0pvU2sxUWNFVk9jRU53WWpCbGFGbERaVkU5UFFvdExTMHRMVVZPUkNCU1UwRWdVRkpKVmtGVVJTQkxSVmt0TFMwdExRbz0K
